In [1]:
# import data
import numpy as np
from numpy import linalg as LA
from functions import ClusterMerits, AuxiliarFunctions
from sklearn import preprocessing

data_path = '/home/micael/MyWorkspace/DATA'
signal = np.load(data_path+'/'+'lvbb125Matrix.npy')[0:5000,:]
signal_trgt = np.ones(signal.shape[0])

ttbar = np.load(data_path+'/'+'TTbarMatrix.npy')
bkg = ttbar
bkg_trgt = np.zeros(bkg.shape[0])

data = np.append(signal,bkg,axis=0)
trgt = np.append(signal_trgt,bkg_trgt,axis=0)


In [3]:
signal_center = ClusterMerits.Baricenter(data[trgt==1,:])
bkg_center = ClusterMerits.Baricenter(data[trgt==0,:])

np.min(signal_center),np.min(bkg_center)

list_cluster = [signal,bkg]
F_0 = ClusterMerits.DispTotal(data,ClusterMerits.Baricenter(data),media='')
F_o = ClusterMerits.DispInterClass(list_cluster,data)
F_i = ClusterMerits.DispIntraClass(list_cluster)

F_o + F_i , F_0

(203658708.10461092, 203658708.10461017)

In [5]:
# normalization CRITICAL
norm_signal = preprocessing.scale(signal)
norm_bkg = preprocessing.scale(bkg)
scl_data = np.append(norm_signal,norm_bkg,axis=0)

list_c = [norm_signal,norm_bkg]
f_0 = ClusterMerits.DispTotal(scl_data,ClusterMerits.Baricenter(scl_data),media='')
f_o = ClusterMerits.DispInterClass(list_c,scl_data)
f_i = ClusterMerits.DispIntraClass(list_c)

f_o + f_i , f_0


(239999.99999999921, 240000.00000000073)

In [9]:
# data set for testing
from sklearn.datasets.samples_generator import make_blobs

n_samples=1000
n_features=2
centers=[[-1,-1],[1,1]] 
cluster_std=1.0

X, y = make_blobs(n_samples, n_features, centers, cluster_std,
                  random_state=None)

X,y

(array([[ 0.06904061, -1.46098615],
        [ 0.42471006, -1.20902896],
        [-1.72693761, -3.26248518],
        ..., 
        [ 0.27699744,  0.40195786],
        [ 2.26697508,  1.08820612],
        [ 0.00647442,  1.60129094]]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
        1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
        0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
        1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1

In [14]:
C_1 = ClusterMerits.Baricenter(X[y==0,:])
C_2 = ClusterMerits.Baricenter(X[y==1,:])
print C_1,C_2
dataSetCenters = np.append(C_1[:,np.newaxis].T,C_2[:,np.newaxis].T,axis=0)
dataSetCenters

[-0.92083413 -0.9779655 ] [ 1.0491529   1.03614153]


array([[-0.92083413, -0.9779655 ],
       [ 1.0491529 ,  1.03614153]])

In [16]:
sinapses = np.array([[-3.342,  -2.433 ],
       [3.465,  2.456]])
sinapses

array([[-3.342, -2.433],
       [ 3.465,  2.456]])

In [17]:
for ievnt in range(X.shape[0]):
    
    if y[ievnt]==0:
        print '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
        print 'sinapse 1 antes', sinapses[0,:]
        sinapses[0,:] = (sinapses[0,:] + 0.1*(X[ievnt,:]-sinapses[0,:]))
        print 'sinapse 1 depois', sinapses[0,:]
        print 'real', dataSetCenters[0,:]
        print '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
    else:
        print 'c2'
        
    

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sinapse 1 antes [-3.342 -2.433]
sinapse 1 depois [-3.00089594 -2.33579862]
real [-0.92083413 -0.9779655 ]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sinapse 1 antes [-3.00089594 -2.33579862]
sinapse 1 depois [-2.65833534 -2.22312165]
real [-0.92083413 -0.9779655 ]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sinapse 1 antes [-2.65833534 -2.22312165]
sinapse 1 depois [-2.56519557 -2.327058  ]
real [-0.92083413 -0.9779655 ]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sinapse 1 antes [-2.56519557 -2.327058  ]
sinapse 1 depois [-2.35334485 -2.03875512]
real [-0.92083413 -0.9779655 ]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~