In [ ]:
# Authors: Isabella Silva Ferreira and Micael Veríssimo de Araújo
# e-mails: (is_bella21@hotmail.com)    (micaelvero@hotmail.com)


In [21]:
# Read data File and sapare the all the sets
import os
import pickle
import numpy as np
import time

from sklearn.decomposition import PCA
from sklearn.externals import joblib

print "All Right!"

All Right!


In [2]:
# Confirm our array shape
data = np.load("/home/micael/MyWorkspace/DATA/lvbb125Array.npy")
data_target = data[:,12]

data_inputs = data[:,:12]
print data.shape
data

(191100, 13)


array([[  9.52196307e-03,   6.12077856e-05,   1.65209174e-02, ...,
          9.21870469e+01,   5.98104895e+01,   6.10195977e+01],
       [  1.67018827e-02,   1.13179535e-01,   9.47747454e-02, ...,
          1.07602320e+02,   5.98104895e+01,   6.44654687e+01],
       [  8.95111356e-03,   9.14592529e-05,   8.82276613e-03, ...,
          3.70010500e+02,   4.97765697e+01,   1.06724656e+02],
       ..., 
       [  1.62160210e-02,   5.48769441e-03,   2.28184238e-02, ...,
          3.86259570e+01,   3.57536859e+01,   3.39022539e+01],
       [  1.42509257e-02,   1.21706940e-01,   4.58930284e-02, ...,
          1.07292875e+02,   5.50991584e+01,   9.68779375e+01],
       [  1.58070903e-02,   4.79239076e-02,   1.20003656e-01, ...,
          6.82103906e+01,   5.50991584e+01,   5.35117266e+01]])

In [3]:
print data_inputs.shape
data_inputs

(191100, 12)


array([[  9.52196307e-03,   6.12077856e-05,   1.65209174e-02, ...,
         -1.83297706e+00,   9.21870469e+01,   5.98104895e+01],
       [  1.67018827e-02,   1.13179535e-01,   9.47747454e-02, ...,
          1.78017831e+00,   1.07602320e+02,   5.98104895e+01],
       [  8.95111356e-03,   9.14592529e-05,   8.82276613e-03, ...,
          5.18436611e-01,   3.70010500e+02,   4.97765697e+01],
       ..., 
       [  1.62160210e-02,   5.48769441e-03,   2.28184238e-02, ...,
         -2.27387905e+00,   3.86259570e+01,   3.57536859e+01],
       [  1.42509257e-02,   1.21706940e-01,   4.58930284e-02, ...,
         -1.46886933e+00,   1.07292875e+02,   5.50991584e+01],
       [  1.58070903e-02,   4.79239076e-02,   1.20003656e-01, ...,
         -3.02542996e+00,   6.82103906e+01,   5.50991584e+01]])

In [4]:
print data_target.shape
data_target

(191100,)


array([  61.01959766,   64.46546875,  106.72465625, ...,   33.90225391,
         96.8779375 ,   53.51172656])

In [60]:
# Train NN
#from Functions import LogFunctions as log
from sklearn import cross_validation
from sklearn import preprocessing

from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD
import keras.callbacks as callbacks
from keras.utils import np_utils

from datetime import datetime  
from datetime import timedelta 


# Train information 
n_folds = 2
n_inits = 1
norm = 'mapstd'

train_info = {}
train_info['n_folds'] = n_folds
train_info['n_inits'] = n_inits
train_info['norm'] = norm

print "CVO"

#CVO = cross_validation.StratifiedKFold(data_target, train_info['n_folds'])

#print "FIM CVO"

#CVO = list(CVO)
#train_info['CVO'] = CVO

#CVO.train = 
test_index = np.random.randint(0, data_target.shape[0], np.floor(0.1*data_target.shape[0])) 

print test_index, "index good"

#for ifold in range(train_info['n_folds']):
#    print "COMECOU FOR"
#    train_id, test_id = CVO[ifold]
    
    # normalize data based in train set
#    if train_info['norm'] == 'mapstd':
#        scaler = preprocessing.StandardScaler().fit(data_inputs[train_id,:])
#    elif train_info['norm'] == 'mapstd_rob':
#        scaler = preprocessing.RobustScaler().fit(data_inputs[train_id,:])
#    elif train_info['norm'] == 'mapminmax':
#        scaler = preprocessing.MinMaxScaler().fit(data_inputs[train_id,:])
        
    #norm_all_data = scaler.transform(data_input)


print "All Right!"

CVO
[ 17350  28548  57047 ...,  63445 165905   1209] index good
All Right!


/home/micael/.virtualenvs/MyAnalysis/lib/python2.7/site-packages/ipykernel/__main__.py:36: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [61]:
index = np.ndarray.tolist(test_index)
print len(index)
print test_index.shape

19110
(19110,)


In [62]:
lista_ind = np.asarray(range(0, data_inputs.shape[0]))

print lista_ind.shape

(191100,)


In [64]:
d = set(lista_ind).intersection(set(test_index))

#lista_treino = np.delete(lista_ind, index)
print set(test_index)
#print data_inputs[index,:].shape
#print data_inputs[d,:].shape


set([160396, 163844, 87382, 98314, 131086, 65552, 98321, 19, 169124, 163863, 98329, 163866, 28, 127663, 5, 65569, 34, 65571, 25097, 98349, 163888, 32817, 22463, 154942, 163892, 98357, 32822, 131127, 92852, 131134, 176765, 64, 32833, 131138, 67, 65607, 157125, 76471, 148960, 98386, 54627, 131159, 131166, 168037, 131168, 32865, 98402, 99, 163940, 98405, 131174, 32872, 131177, 131178, 108, 65645, 98414, 32879, 131188, 55429, 153150, 152762, 122, 65659, 98430, 163967, 32898, 32899, 98436, 56743, 98420, 65671, 137, 65674, 32908, 131213, 98446, 120173, 180248, 32916, 177859, 25, 185497, 32921, 87407, 180250, 43717, 164001, 147483, 157128, 98469, 167, 170, 164011, 164015, 98482, 98484, 164021, 164022, 65719, 184, 32953, 186, 32955, 183316, 131263, 164033, 65731, 131268, 98501, 198, 13100, 200, 32970, 21879, 16418, 65742, 208, 32977, 93844, 211, 212, 164054, 98519, 164056, 131292, 222, 223, 98528, 65764, 131301, 131302, 54564, 233, 131307, 65772, 125650, 131310, 164079, 65777, 243, 33012, 6578

In [ ]:
print b_matrix.shape
b_matrix

In [ ]:
Al_matrix_1 = np.empty([np.floor(0.1*data_inputs.shape[0]),data_inputs.shape[1]], dtype = float)
Al_matrix_2 = np.empty([np.floor(0.9*data_inputs.shape[0]),data_inputs.shape[1]], dtype = float)
for i in range(data.shape[0]-1):
    if i in index:
        np.append(Al_matrix_1, data_inputs[i,:])
    else:
        np.append(Al_matrix_2, data_inputs[i,:])
print Al_matrix_1.shape
Al_matrix_1


In [ ]:
print Al_matrix_2.shape
Al_matrix_2

In [28]:
# MOP test_index

[freq, target_values] = np.histogram(data_target[test_index],
             bins=np.linspace(data_target[test_index].min(),data_target[test_index].max(),50))

MOP = target_values[np.argmax(freq)]

print MOP

56.3359648836
